#!/bin/bash

# dvsmu v.2.01 에서 버전 확인시 참조하는 내용

#===================================
SCRIPT_VERSION="2.01"
#===================================

if [ "$1" != "" ]; then
    case $1 in
        -v|-V|--version) echo $SCRIPT_VERSION; exit 0 ;;
    esac
fi


