#!/bin/bash
# 배포용 setup 파일

TMPDIR=$(mktemp -d)

cat << 'EOF2' | base64 -d | gunzip > "$TMPDIR/setup_original"
H4sICJCFnWgAA3Rlc3Rfb3JpAFNW1E/KzNNPSizO4OJKTc7IV1AqycgsVgCiRIWS1OISJS4gAAAE
WwgrJgAAAA==
EOF2

# 실행
bash "$TMPDIR/setup_original"

# 임시 파일 삭제
rm -rf "$TMPDIR"
