#!/bin/bash

source /var/lib/dvswitch/dvs/var.txt

#------------------------------------------------------
function bm_watchdog_test() {
clear
sel=$(whiptail --title " bm_watchdog_test " --menu "\
\n
" 18 45 10 \
"1" "DMR_Hosts.txt" \
"2" "bm_present_list.txt" \
"3" "bm_watchdog_status.txt" \
"4" "reserved" \
"5" "실행" \
"6" "var.txt" \
"7" "var01.txt" \
"8" "var03.txt" \
"9" "var05.txt" \
"10" "LOG" \
3>&1 1>&2 2>&3)

if [ $? != 0 ]; then ${DVS}dvsman; exit 0; fi

case $sel in
1)
sudo nano /var/lib/mmdvm/DMR_Hosts.txt; ${DVS}dvsman bm_test; exit 0 ;;
2)
sudo nano /var/tmp/bm_present_list.txt; ${DVS}dvsman bm_test; exit 0 ;;
3)
sudo nano /var/tmp/bm_watchdog_status.txt; ${DVS}dvsman bm_test; exit 0 ;;
4)
sudo nano /var/lib/mmdvm/DMR_Hosts.txt; ${DVS}dvsman bm_test; exit 0 ;;
5)
${DVS}dvsman bm_test; exit 0 ;;
6)
sudo nano /var/lib/dvswitch/dvs/var.txt; ${DVS}dvsman bm_test; exit 0 ;;
7)
sudo nano /var/lib/dvswitch/dvs/var01.txt; ${DVS}dvsman bm_test; exit 0 ;;
8)
sudo nano /var/lib/dvswitch/dvs/var03.txt; ${DVS}dvsman bm_test; exit 0 ;;
9)
sudo nano /var/lib/dvswitch/dvs/var05.txt; ${DVS}dvsman bm_test; exit 0 ;;
10)
sudo nano /var/log/dvswitch/bm_watchdog.log; ${DVS}dvsman bm_test; exit 0 ;;
esac
}
#------------------------------------------------------
function lan() {
clear
sel=$(whiptail --title " LANGUAGE " --menu "\
\n
" 16 45 8 \
"1" "template.txt" \
"2" "korean.txt" \
"3" "english.txt" \
"4" "japanese.txt" \
"5" "german.txt" \
"6" "greek.txt" \
"7" "polish.txt" \
"8" "language.txt" \
3>&1 1>&2 2>&3)

if [ $? != 0 ]; then ${DVS}dvsman; exit 0; fi

case $sel in
1)
sudo nano /var/lib/dvswitch/dvs/lan/template.txt; ${DVS}dvsman lan; exit 0 ;;
2)
sudo nano /var/lib/dvswitch/dvs/lan/korean.txt; ${DVS}dvsman lan; exit 0 ;;
3)
sudo nano /var/lib/dvswitch/dvs/lan/english.txt; ${DVS}dvsman lan; exit 0 ;;
4)
sudo nano /var/lib/dvswitch/dvs/lan/japanese.txt; ${DVS}dvsman lan; exit 0 ;;
5)
sudo nano /var/lib/dvswitch/dvs/lan/german.txt; ${DVS}dvsman lan; exit 0 ;;
6)
sudo nano /var/lib/dvswitch/dvs/lan/greek.txt; ${DVS}dvsman lan; exit 0 ;;
7)
sudo nano /var/lib/dvswitch/dvs/lan/polish.txt; ${DVS}dvsman lan; exit 0 ;;
8)
sudo nano /var/lib/dvswitch/dvs/lan/language.txt; ${DVS}dvsman lan; exit 0 ;;
esac
}

#------------------------------------------------------
function tgdb_en() {
clear
sel=$(whiptail --title " TGDB EN " --menu "\
\n
" 13 45 5 \
"1" "DMR_fvrt_list.txt" \
"2" "DSTAR_fvrt_list.txt" \
"3" "NXDN_fvrt_list.txt" \
"4" "P25_fvrt_list.txt" \
"5" "YSF_fvrt_list.txt" \
3>&1 1>&2 2>&3)

if [ $? != 0 ]; then ${DVS}dvsman tgdb; exit 0; fi

case $sel in
1)
sudo nano /var/lib/dvswitch/dvs/tgdb/EN/DMR_fvrt_list.txt; ${DVS}dvsman tgdb_en; exit 0 ;;
2)
sudo nano /var/lib/dvswitch/dvs/tgdb/EN/DSTAR_fvrt_list.txt; ${DVS}dvsman tgdb_en; exit 0 ;;
3)
sudo nano /var/lib/dvswitch/dvs/tgdb/EN/NXDN_fvrt_list.txt; ${DVS}dvsman tgdb_en; exit 0 ;;
4)
sudo nano /var/lib/dvswitch/dvs/tgdb/EN/P25_fvrt_list.txt; ${DVS}dvsman tgdb_en; exit 0 ;;
5)
sudo nano /var/lib/dvswitch/dvs/tgdb/EN/YSF_fvrt_list.txt; ${DVS}dvsman tgdb_en; exit 0 ;;
esac
}

#------------------------------------------------------
function tgdb_kr() {
clear
sel=$(whiptail --title " TGDB KR " --menu "\
\n
" 13 45 5 \
"1" "DMR_fvrt_list.txt" \
"2" "DSTAR_fvrt_list.txt" \
"3" "NXDN_fvrt_list.txt" \
"4" "P25_fvrt_list.txt" \
"5" "YSF_fvrt_list.txt" \
3>&1 1>&2 2>&3)

if [ $? != 0 ]; then ${DVS}dvsman tgdb; exit 0; fi

case $sel in
1)
sudo nano /var/lib/dvswitch/dvs/tgdb/KR/DMR_fvrt_list.txt; ${DVS}dvsman tgdb_kr; exit 0 ;;
2)
sudo nano /var/lib/dvswitch/dvs/tgdb/KR/DSTAR_fvrt_list.txt; ${DVS}dvsman tgdb_kr; exit 0 ;;
3)
sudo nano /var/lib/dvswitch/dvs/tgdb/KR/NXDN_fvrt_list.txt; ${DVS}dvsman tgdb_kr; exit 0 ;;
4)
sudo nano /var/lib/dvswitch/dvs/tgdb/KR/P25_fvrt_list.txt; ${DVS}dvsman tgdb_kr; exit 0 ;;
5)
sudo nano /var/lib/dvswitch/dvs/tgdb/KR/YSF_fvrt_list.txt; ${DVS}dvsman tgdb_kr; exit 0 ;;
esac
}

#------------------------------------------------------
function tgdb() {
clear
sel=$(whiptail --title " TGDB " --menu "\
\n
" 20 45 12 \
"1" "DMR_fvrt_list.txt" \
"2" "DMR_node_list.txt" \
"3" "DSTAR_fvrt_list.txt" \
"4" "DSTAR_node_list.txt" \
"5" "NXDN_fvrt_list.txt" \
"6" "NXDN_node_list.txt" \
"7" "P25_fvrt_list.txt" \
"8" "P25_node_list.txt" \
"9" "YSF_fvrt_list.txt" \
"10" "YSF_node_list.txt" \
"11" "TGDB EN ----->" \
"12" "TGDB KR ----->" \
3>&1 1>&2 2>&3)

if [ $? != 0 ]; then ${DVS}dvsman; exit 0; fi

case $sel in
1)
sudo nano /var/lib/dvswitch/dvs/tgdb/DMR_fvrt_list.txt; ${DVS}dvsman tgdb; exit 0 ;;
2)
sudo nano /var/lib/dvswitch/dvs/tgdb/DMR_node_list.txt; ${DVS}dvsman tgdb; exit 0 ;;
3)
sudo nano /var/lib/dvswitch/dvs/tgdb/DSTAR_fvrt_list.txt; ${DVS}dvsman tgdb; exit 0 ;;
4)
sudo nano /var/lib/dvswitch/dvs/tgdb/DSTAR_node_list.txt; ${DVS}dvsman tgdb; exit 0 ;;
5)
sudo nano /var/lib/dvswitch/dvs/tgdb/NXDN_fvrt_list.txt; ${DVS}dvsman tgdb; exit 0 ;;
6)
sudo nano /var/lib/dvswitch/dvs/tgdb/NXDN_node_list.txt; ${DVS}dvsman tgdb; exit 0 ;;
7)
sudo nano /var/lib/dvswitch/dvs/tgdb/P25_fvrt_list.txt; ${DVS}dvsman tgdb; exit 0 ;;
8)
sudo nano /var/lib/dvswitch/dvs/tgdb/P25_node_list.txt; ${DVS}dvsman tgdb; exit 0 ;;
9)
sudo nano /var/lib/dvswitch/dvs/tgdb/YSF_fvrt_list.txt; ${DVS}dvsman tgdb; exit 0 ;;
10)
sudo nano /var/lib/dvswitch/dvs/tgdb/YSF_node_list.txt; ${DVS}dvsman tgdb; exit 0 ;;
11)
tgdb_en; exit 0 ;;
12)
tgdb_kr; exit 0 ;;
esac
}


#------------------------------------------------------
function adv_en() {
clear
sel=$(whiptail --title " ADV EN " --menu "\
\n
" 18 45 10 \
"1" "adv_audio.txt" \
"2" "adv_dmr.txt" \
"3" "adv_hotspot.txt" \
"4" "adv_main.txt" \
"5" "adv_managetg.txt" \
"6" "adv_resetfvrt.txt" \
"7" "adv_rxgain.txt" \
"8" "adv_txgain.txt" \
"9" "adv_tgref.txt" \
"10" "adv_tools.txt" \
3>&1 1>&2 2>&3)

if [ $? != 0 ]; then ${DVS}dvsman adv; exit 0; fi

case $sel in
1)
sudo nano /var/lib/dvswitch/dvs/adv/EN/adv_audio.txt; ${DVS}dvsman adv_en; exit 0 ;;
2)
sudo nano /var/lib/dvswitch/dvs/adv/EN/adv_dmr.txt; ${DVS}dvsman adv_en; exit 0 ;;
3)
sudo nano /var/lib/dvswitch/dvs/adv/EN/adv_hotspot.txt; ${DVS}dvsman adv_en; exit 0 ;;
4)
sudo nano /var/lib/dvswitch/dvs/adv/EN/adv_main.txt; ${DVS}dvsman adv_en; exit 0 ;;
5)
sudo nano /var/lib/dvswitch/dvs/adv/EN/adv_managetg.txt; ${DVS}dvsman adv_en; exit 0 ;;
6)
sudo nano /var/lib/dvswitch/dvs/adv/EN/adv_resetfvrt.txt; ${DVS}dvsman adv_en; exit 0 ;;
7)
sudo nano /var/lib/dvswitch/dvs/adv/EN/adv_rxgain.txt; ${DVS}dvsman adv_en; exit 0 ;;
8)
sudo nano /var/lib/dvswitch/dvs/adv/EN/adv_txgain.txt; ${DVS}dvsman adv_en; exit 0 ;;
9)
sudo nano /var/lib/dvswitch/dvs/adv/EN/adv_tgref.txt; ${DVS}dvsman adv_en; exit 0 ;;
10)
sudo nano /var/lib/dvswitch/dvs/adv/EN/adv_tools.txt; ${DVS}dvsman adv_en; exit 0 ;;
esac
}

#------------------------------------------------------
function adv_kr() {
clear
sel=$(whiptail --title " ADV KR " --menu "\
\n
" 18 45 10 \
"1" "adv_audio.txt" \
"2" "adv_dmr.txt" \
"3" "adv_hotspot.txt" \
"4" "adv_main.txt" \
"5" "adv_managetg.txt" \
"6" "adv_resetfvrt.txt" \
"7" "adv_rxgain.txt" \
"8" "adv_txgain.txt" \
"9" "adv_tgref.txt" \
"10" "adv_tools.txt" \
3>&1 1>&2 2>&3)

if [ $? != 0 ]; then ${DVS}dvsman adv; exit 0; fi

case $sel in
1)
sudo nano /var/lib/dvswitch/dvs/adv/KR/adv_audio.txt; ${DVS}dvsman adv_kr; exit 0 ;;
2)
sudo nano /var/lib/dvswitch/dvs/adv/KR/adv_dmr.txt; ${DVS}dvsman adv_kr; exit 0 ;;
3)
sudo nano /var/lib/dvswitch/dvs/adv/KR/adv_hotspot.txt; ${DVS}dvsman adv_kr; exit 0 ;;
4)
sudo nano /var/lib/dvswitch/dvs/adv/KR/adv_main.txt; ${DVS}dvsman adv_kr; exit 0 ;;
5)
sudo nano /var/lib/dvswitch/dvs/adv/KR/adv_managetg.txt; ${DVS}dvsman adv_kr; exit 0 ;;
6)
sudo nano /var/lib/dvswitch/dvs/adv/KR/adv_resetfvrt.txt; ${DVS}dvsman adv_kr; exit 0 ;;
7)
sudo nano /var/lib/dvswitch/dvs/adv/KR/adv_rxgain.txt; ${DVS}dvsman adv_kr; exit 0 ;;
8)
sudo nano /var/lib/dvswitch/dvs/adv/KR/adv_txgain.txt; ${DVS}dvsman adv_kr; exit 0 ;;
9)
sudo nano /var/lib/dvswitch/dvs/adv/KR/adv_tgref.txt; ${DVS}dvsman adv_kr; exit 0 ;;
10)
sudo nano /var/lib/dvswitch/dvs/adv/KR/adv_tools.txt; ${DVS}dvsman adv_kr; exit 0 ;;
esac
}

#------------------------------------------------------
function adv() {
clear
sel=$(whiptail --title " ADV " --menu "\
\n
" 12 45 4 \
"1" "dvsm.macro" \
"2" "dvsm.sh" \
"3" "EN ----->" \
"4" "KR ----->" \
3>&1 1>&2 2>&3)

if [ $? != 0 ]; then ${DVS}dvsman; exit 0; fi

case $sel in
1)
sudo nano /var/lib/dvswitch/dvs/adv/dvsm.macro;  ${DVS}dvsman adv; exit 0 ;;
2)
sudo nano /var/lib/dvswitch/dvs/adv/dvsm.sh;  ${DVS}dvsman adv; exit 0 ;;
3)
adv_en; exit 0 ;;
4)
adv_kr; exit 0 ;;
esac
}

#------------------------------------------------------
function host() {
clear
sel=$(whiptail --title " HOST " --menu "\
\n
" 21 45 13 \
"1" "APRS_Hosts.txt" \
"2" "DCS_Hosts.txt" \
"3" "DExtra_Hosts.txt" \
"4" "DMR_Hosts.txt" \
"5" "DPlus_Hosts.txt" \
"6" "NXDNHostss.txt" \
"7" "private_NXDNHosts.txt" \
"8" "P25Hosts..txt" \
"9" "private_P25Hosts.txt" \
"10" "YSFHosts.txt" \
"11" "XLXHosts.txt" \
"12" "FCSRooms.txt" \
"13" "DMRIds.dat" \
3>&1 1>&2 2>&3)

if [ $? != 0 ]; then ${DVS}dvsman; exit 0; fi

case $sel in
1)
sudo nano /var/lib/mmdvm/APRS_Hosts.txt; ${DVS}dvsman host; exit 0 ;;
2)
sudo nano /var/lib/mmdvm/DCS_Hosts.txt; ${DVS}dvsman host; exit 0 ;;
3)
sudo nano /var/lib/mmdvm/DExtra_Hosts.txt; ${DVS}dvsman host; exit 0 ;;
4)
sudo nano /var/lib/mmdvm/DMR_Hosts.txt; ${DVS}dvsman host; exit 0 ;;
5)
sudo nano /var/lib/mmdvm/DPlus_Hosts.txt; ${DVS}dvsman host; exit 0 ;;
6)
sudo nano /var/lib/mmdvm/NXDNHostss.txt; ${DVS}dvsman host; exit 0 ;;
7)
sudo nano /var/lib/mmdvm/private_NXDNHosts.txt; ${DVS}dvsman host; exit 0 ;;
8)
sudo nano /var/lib/mmdvm/P25Hosts.txt; ${DVS}dvsman host; exit 0 ;;
9)
sudo nano /var/lib/mmdvm/private_P25Hosts.txt; ${DVS}dvsman host; exit 0 ;;
10)
sudo nano /var/lib/mmdvm/YSFHosts.txt; ${DVS}dvsman host; exit 0 ;;
11)
sudo nano /var/lib/mmdvm/XLXHosts.txt; ${DVS}dvsman host; exit 0 ;;
12)
sudo nano /var/lib/mmdvm/FCSRooms.txt; ${DVS}dvsman host; exit 0 ;;
13)
sudo nano /var/lib/mmdvm/DMRIds.dat; ${DVS}dvsman host; exit 0 ;;
esac
}

#------------------------------------------------------
function ini() {
clear
sel=$(whiptail --title " INI " --menu "\
\n
" 17 45 9 \
"1" "var.txt" \
"2" "func.txt" \
"3" "MMDVM_Bridge.ini" \
"4" "Analog_Bridge.ini" \
"5" "DVSwitch.ini" \
"6" "dvswitch.sh" \
"7" "dvsm.macro" \
"8" "dvsm.sh" \
"9" "dvswitch.sh" \
3>&1 1>&2 2>&3)

if [ $? != 0 ]; then ${DVS}dvsman; exit 0; fi

case $sel in
1)
sudo nano /var/lib/dvswitch/dvs/var.txt; ${DVS}dvsman ini; exit 0 ;;
2)
sudo nano /var/lib/dvswitch/dvs/func.txt; ${DVS}dvsman ini; exit 0 ;;
3)
sudo nano /opt/MMDVM_Bridge/MMDVM_Bridge.ini; ${DVS}dvsman ini; exit 0 ;;
4)
sudo nano /opt/Analog_Bridge/Analog_Bridge.ini; ${DVS}dvsman ini; exit 0 ;;
5)
sudo nano /opt/MMDVM_Bridge/DVSwitch.ini; ${DVS}dvsman ini; exit 0 ;;
6)
sudo nano /opt/MMDVM_Bridge/dvswitch.sh; ${DVS}dvsman ini; exit 0 ;;
7)
sudo nano /opt/Analog_Bridge/dvsm.macro; ${DVS}dvsman ini; exit 0 ;;
8)
sudo nano /opt/Analog_Bridge/dvsm.sh; ${DVS}dvsman ini; exit 0 ;;
9)
sudo nano /opt/MMDVM_Bridge/dvswitch.sh; ${DVS}dvsman ini; exit 0 ;;
esac
}

#------------------------------------------------------
function dvs_file() {
clear
sel=$(whiptail --title " DVS FILES " --menu "\
\n
" 30 45 22 \
"1" "88_restart.sh" \
"2" "99_reboot.sh" \
"3" "adhoc_adv.sh" \
"4" "adhoc_basic.sh" \
"5" "adhoc_check.sh" \
"6" "adnl_dmr.sh" \
"7" "adv_config_menu.sh" \
"8" "auto_upgrade.sh" \
"9" "clone.sh" \
"10" "config_ini.sh" \
"11" "DMRIds_chk.sh" \
"12" "dvs" \
"13" "dvsb" \
"14" "init_config,sh" \
"15" "language,sh" \
"16" "man_log" \
"17" "temp_msg,sh" \
"18" "temp,sh" \
"19" "tgdb,sh" \
"20" "tools_menu,sh" \
"21" "update_upgrade,sh" \
"22" "upgrade,sh" \
3>&1 1>&2 2>&3)

if [ $? != 0 ]; then ${DVS}dvsman; exit 0; fi

case $sel in
1)
sudo nano /usr/local/dvs/88_restart.sh; ${DVS}dvsman dvs_file; exit 0 ;;
2)
sudo nano /usr/local/dvs/99_reboot.sh; ${DVS}dvsman dvs_file; exit 0 ;;
3)
sudo nano /usr/local/dvs/adhoc_adv.sh; ${DVS}dvsman dvs_file; exit 0 ;;
4)
sudo nano /usr/local/dvs/adhoc_basic.sh; ${DVS}dvsman dvs_file; exit 0 ;;
5)
sudo nano /usr/local/dvs/adhoc_check.sh; ${DVS}dvsman dvs_file; exit 0 ;;
6)
sudo nano /usr/local/dvs/adnl_dmr.sh; ${DVS}dvsman dvs_file; exit 0 ;;
7)
sudo nano /usr/local/dvs/adv_config_menu.sh; ${DVS}dvsman dvs_file; exit 0 ;;
8)
sudo nano /usr/local/dvs/auto_upgrade.sh; ${DVS}dvsman dvs_file; exit 0 ;;
9)
sudo nano /usr/local/dvs/clone.sh; ${DVS}dvsman dvs_file; exit 0 ;;
10)
sudo nano /usr/local/dvs/config_ini.sh; ${DVS}dvsman dvs_file; exit 0 ;;
11)
sudo nano /usr/local/dvs/DMRIds_chk.sh; ${DVS}dvsman dvs_file; exit 0 ;;
12)
sudo nano /usr/local/dvs/dvs; ${DVS}dvsman dvs_file; exit 0 ;;
13)
sudo nano /usr/local/dvs/dvsb; ${DVS}dvsman dvs_file; exit 0 ;;
14)
sudo nano /usr/local/dvs/init_config.sh; ${DVS}dvsman dvs_file; exit 0 ;;
15)
sudo nano /usr/local/dvs/language.sh; ${DVS}dvsman dvs_file; exit 0 ;;
16)
sudo nano /usr/local/dvs/man_log; ${DVS}dvsman dvs_file; exit 0 ;;
17)
sudo nano /usr/local/dvs/temp_msg.sh; ${DVS}dvsman dvs_file; exit 0 ;;
18)
sudo nano /usr/local/dvs/temp.sh; ${DVS}dvsman dvs_file; exit 0 ;;
19)
sudo nano /usr/local/dvs/tgdb.sh; ${DVS}dvsman dvs_file; exit 0 ;;
20)
sudo nano /usr/local/dvs/tools_menu.sh; ${DVS}dvsman dvs_file; exit 0 ;;
21)
sudo nano /usr/local/dvs/update_upgrade.sh; ${DVS}dvsman dvs_file; exit 0 ;;
22)
sudo nano /usr/local/dvs/upgrade.sh; ${DVS}dvsman dvs_file; exit 0 ;;
esac
}

#-------------------------------------------------------------
function log() {
clear
sel=$(whiptail --title " 로그 확인 " --menu "\
\n
" 15 50 6 \
"1" "dvsmu.log 열기" \
"2" "auto_upgrade.log 열기" \
"3" "bm_watchdog.txt 열기" \
"4" "dvsstart-runner.sh 열기" \
"5" "crontab 열기" \
"6" "Back to Main" \
3>&1 1>&2 2>&3)

if [ $? != 0 ]; then ${DVS}dvsman; exit 0
fi

case $sel in
1)
if [ ! -e /var/log/dvswitch/dvsmu.log ]; then
        echo "This is a Log file for dvsMU" | sudo tee /var/log/dvswitch/dvsmu.log > /dev/null 2>&1
        log_line=--------------------------------------------------
        sudo sed -i "1 i\\$log_line" /var/log/dvswitch/dvsmu.log
fi
sudo nano /var/log/dvswitch/dvsmu.log; ${DVS}dvsman log; exit 0 ;;
2)
sudo nano /var/log/dvswitch/auto_upgrade.log; ${DVS}dvsman log; exit 0 ;;
3)
sudo nano /var/log/dvswitch/bm_watchdog.log; ${DVS}dvsman log; exit 0 ;;
4)
sudo nano /var/log/dvswitch/dvsstart-run.log; ${DVS}dvsman log; exit 0 ;;
5)
sudo nano /etc/crontab; ${DVS}dvsman log; exit 0 ;;
6)
${DVS}dvsman; exit 0 ;;
esac
}


#== MAIN SCRIPT ============================================
clear

if [ "$1" = lan ]; then lan; fi
if [ "$1" = tgdb ]; then tgdb; fi
if [ "$1" = tgdb_en ]; then tgdb_en; fi
if [ "$1" = tgdb_kr ]; then tgdb_kr; fi
if [ "$1" = adv ]; then adv; fi
if [ "$1" = adv_en ]; then adv_en; fi
if [ "$1" = adv_kr ]; then adv_kr; fi
if [ "$1" = host ]; then host; fi
if [ "$1" = ini ]; then ini; fi
if [ "$1" = dvs_file ]; then dvs_file; fi
if [ "$1" = sys ]; then sys; fi
if [ "$1" = log ]; then log; fi
if [ "$1" = bm_test ]; then bm_watchdog_test; fi

sel=$(whiptail --title " DVS Management " --menu "\
\n
" 18 45 10 \
"1" "DVS FILES" \
"2" "INI FILES" \
"3" "LANGUAGE" \
"4" "TGDB" \
"5" "ADV" \
"6" "HOST" \
"7" "SYS" \
"8" "LOG" \
"9" "crontab" \
"10" "bm_watchdog TEST" \
3>&1 1>&2 2>&3)

case $sel in
1)
dvs_file; ${DVS}dvsman; exit 0 ;;
2)
ini; ${DVS}dvsman; exit 0 ;;
3)
lan; ${DVS}dvsman; exit 0 ;;
4)
tgdb; ${DVS}dvsman; exit 0 ;;
5)
adv; ${DVS}dvsman; exit 0 ;;
6)
host; ${DVS}dvsman; exit 0 ;;
7)
sys; ${DVS}dvsman; exit 0 ;;
8)
log; ${DVS}dvsman; exit 0 ;;
9)
sudo nano /etc/crontab; ${DVS}dvsman; exit 0 ;;
10)
bm_watchdog_test; ${DVS}dvsman; exit 0 ;;
esac






